<?php
return [
    'GET' => [
        '' => ['AuthController', 'loginForm'],
        'login' => ['AuthController', 'loginForm'],
        'logout' => ['AuthController', 'logout'],
        'dashboard' => ['DashboardController', 'index'],
        'clientes' => ['ClienteController', 'index'],
        'clientes/nuevo' => ['ClienteController', 'create'],
        'clientes/ver' => ['ClienteController', 'show'],
        'visitas' => ['VisitaController', 'index'],
        'ventas' => ['VentaController', 'index'],
        'ventas/validar' => ['VentaController', 'pendientesValidacion'],
        'comisiones' => ['ComisionController', 'index'],
        'tareas' => ['TareaController', 'index'],
        'pipeline' => ['PipelineController', 'index'],
        'export/clientes' => ['ExportController', 'clientes'],
        'api/calendario/eventos' => ['ApiController', 'calendarioEventos'],
    ],
    'POST' => [
        'login' => ['AuthController', 'login'],
        'clientes/guardar' => ['ClienteController', 'store'],
        'clientes/transferir-inpro' => ['AsignacionController', 'transferirInpro'],
        'visitas/guardar' => ['VisitaController', 'store'],
        'visitas/realizar' => ['VisitaController', 'realizar'],
        'visitas/cancelar' => ['VisitaController', 'cancelar'],
        'visitas/reagendar' => ['VisitaController', 'reagendar'],
        'visitas/recordatorio' => ['VisitaController', 'recordatorio'],
        'ventas/guardar' => ['VentaController', 'store'],
        'ventas/validar' => ['VentaController', 'validar'],
        'tareas/guardar' => ['TareaController', 'store'],
        'tareas/completar' => ['TareaController', 'completar'],
        'tareas/mover' => ['TareaController', 'mover'],
        'tareas/destacar' => ['TareaController', 'destacar'],
        'tareas/actualizar' => ['TareaController', 'actualizar'],
        'tareas/eliminar' => ['TareaController', 'eliminar'],
        'tareas/cancelar' => ['TareaController', 'cancelar'],
        'pipeline/mover' => ['PipelineController', 'mover'],
        'contactos/guardar' => ['ContactoController', 'store'],
    ],
];
